# py3status

https://gist.github.com/ultrabug/ee216a38a0152bce4b2cef73ef358603
